[project]
name = "crewai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "ruff>=0.13.2",
]
